const mongoose = require("mongoose");
const dotenv = require("dotenv");
const Service = require("./models/Service"); 

dotenv.config();

const services = [
  {
    id: 1,
    icon: "📸",
    title: "Photography",
    subtitle: "Capture Every Moment",
    desc: "Award-winning photographers who tell your love story through breathtaking imagery. Every smile, every tear, every laugh — preserved forever.",
    price: "Starting from ₹5,000",
    tag: "Most Popular",
    tagColor: "bg-rose-500",
    highlights: ["HD & 4K Coverage", "Same Day Edits", "Online Gallery", "Drone Shots"],
    rating: 4.9,
    reviews: 238,
    img: "https://images.unsplash.com/photo-1519741497674-611481863552?w=800",
    styles: [
      { id: 1, name: "Candid & Natural", desc: "Real emotions, unposed moments", price: 15000, img: "https://images.unsplash.com/photo-1519741497674-611481863552?w=600", specs: [{ label: "Coverage", value: "Full Day (8 hrs)" }, { label: "Photographers", value: "2 Professionals" }, { label: "Edited Photos", value: "500+" }, { label: "Delivery", value: "7 Days" }, { label: "Drone Shots", value: "Included" }, { label: "Online Gallery", value: "Yes, 1 Year Access" }] },
      { id: 2, name: "Traditional Posed", desc: "Classic family & couple portraits", price: 12000, img: "https://images.unsplash.com/photo-1511285560929-80b456fea0bc?w=600", specs: [{ label: "Coverage", value: "Full Day (8 hrs)" }, { label: "Photographers", value: "1 Professional" }, { label: "Edited Photos", value: "300+" }, { label: "Delivery", value: "5 Days" }, { label: "Drone Shots", value: "Not Included" }, { label: "Online Gallery", value: "Yes, 6 Months" }] },
      { id: 3, name: "Cinematic Dark", desc: "Moody, dramatic lighting", price: 18000, img: "https://images.unsplash.com/photo-1606216794074-735e91aa2c92?w=600", specs: [{ label: "Coverage", value: "Full Day (8 hrs)" }, { label: "Photographers", value: "2 Professionals" }, { label: "Edited Photos", value: "600+" }, { label: "Delivery", value: "10 Days" }, { label: "Drone Shots", value: "Included" }, { label: "Studio Lighting", value: "Professional Setup" }] },
      { id: 4, name: "Outdoor Natural", desc: "Golden hour, garden settings", price: 14000, img: "https://images.unsplash.com/photo-1537633552985-df8429e8048b?w=600", specs: [{ label: "Coverage", value: "Half Day (4 hrs)" }, { label: "Photographers", value: "2 Professionals" }, { label: "Edited Photos", value: "400+" }, { label: "Delivery", value: "7 Days" }, { label: "Location", value: "Outdoor / Garden" }, { label: "Golden Hour", value: "Included" }] },
      { id: 5, name: "Pre-Wedding Shoot", desc: "Romantic couple shoot", price: 10000, img: "https://images.unsplash.com/photo-1465495976277-4387d4b0b4c6?w=600", specs: [{ label: "Duration", value: "4 hrs" }, { label: "Photographers", value: "1 Professional" }, { label: "Edited Photos", value: "150+" }, { label: "Delivery", value: "5 Days" }, { label: "Locations", value: "Up to 2" }, { label: "Outfit Changes", value: "2 Allowed" }] },
      { id: 6, name: "Aerial / Drone", desc: "Stunning bird-eye view shots", price: 20000, img: "https://images.unsplash.com/photo-1583939003579-730e3918a45a?w=600", specs: [{ label: "Coverage", value: "Full Day (8 hrs)" }, { label: "Drone Pilot", value: "Licensed FAA Pilot" }, { label: "Edited Photos", value: "300+ Aerial" }, { label: "Video Clips", value: "10+ Aerial Clips" }, { label: "Delivery", value: "10 Days" }, { label: "Resolution", value: "4K Ultra HD" }] },
    ],
  },
  {
    id: 2,
    icon: "🎵",
    title: "DJ & Music",
    subtitle: "Set The Mood",
    desc: "Professional DJs with premium sound systems that transform your event into an electrifying experience. Live bands & orchestras available.",
    price: "Starting from ₹8,000",
    tag: "Top Rated",
    tagColor: "bg-violet-500",
    highlights: ["Live Band Option", "Custom Playlists", "LED Setup", "MC Services"],
    rating: 4.8,
    reviews: 184,
    img: "https://images.unsplash.com/photo-1478146059778-26028b07395a?w=800",
    styles: [
      { id: 1, name: "EDM & Bollywood", desc: "High energy dance floor vibes", price: 15000, img: "https://images.unsplash.com/photo-1478146059778-26028b07395a?w=600", specs: [{ label: "Duration", value: "6 hrs" }, { label: "DJ Setup", value: "Pioneer CDJ + Mixer" }, { label: "Sound System", value: "JBL 2000W" }, { label: "LED Lights", value: "Full Rig Included" }, { label: "Fog Machine", value: "Included" }, { label: "MC", value: "Included" }] },
      { id: 2, name: "Tamil Hits Mix", desc: "Latest & classic Tamil songs", price: 12000, img: "https://images.unsplash.com/photo-1516450360452-9312f5e86fc7?w=600", specs: [{ label: "Duration", value: "5 hrs" }, { label: "DJ Setup", value: "Professional Mixer" }, { label: "Sound System", value: "Bose 1500W" }, { label: "Playlist", value: "Custom Tamil List" }, { label: "LED Lights", value: "Basic Setup" }, { label: "MC", value: "Optional Add-on" }] },
      { id: 3, name: "Live Band", desc: "Live instruments + vocalist", price: 25000, img: "https://images.unsplash.com/photo-1429962714451-bb934ecdc4ec?w=600", specs: [{ label: "Duration", value: "3 hrs" }, { label: "Band Members", value: "5 Musicians" }, { label: "Instruments", value: "Guitar, Keys, Drums, Bass" }, { label: "Vocalist", value: "1 Male + 1 Female" }, { label: "Sound System", value: "Professional PA" }, { label: "Genres", value: "Tamil, Hindi, English" }] },
      { id: 4, name: "Acoustic / Soft", desc: "Calm romantic background music", price: 10000, img: "https://images.unsplash.com/photo-1470225620780-dba8ba36b745?w=600", specs: [{ label: "Duration", value: "4 hrs" }, { label: "Setup", value: "Acoustic Guitar + Keys" }, { label: "Volume", value: "Background Level" }, { label: "Vocalist", value: "1 Included" }, { label: "Suitable For", value: "Dinner / Reception" }, { label: "Playlist", value: "Custom on Request" }] },
      { id: 5, name: "Nadaswaram", desc: "Traditional Tamil wedding music", price: 8000, img: "https://images.unsplash.com/photo-1533174072545-7a4b6ad7a6c3?w=600", specs: [{ label: "Duration", value: "3 hrs" }, { label: "Artists", value: "2 Nadaswaram Players" }, { label: "Thavil", value: "1 Player Included" }, { label: "Suitable For", value: "Muhurtham / Ceremony" }, { label: "Traditional Songs", value: "50+ Repertoire" }, { label: "Attire", value: "Traditional Dress" }] },
      { id: 6, name: "Full LED DJ Setup", desc: "DJ + full LED light show", price: 20000, img: "https://images.unsplash.com/photo-1501386761578-eac5c94b800a?w=600", specs: [{ label: "Duration", value: "8 hrs" }, { label: "LED Wall", value: "Full Backdrop Included" }, { label: "Moving Heads", value: "8 Units" }, { label: "Laser Show", value: "Included" }, { label: "Sound System", value: "JBL 3000W" }, { label: "Fog + Haze", value: "Included" }] },
    ],
  },
  {
    id: 3,
    icon: "🌸",
    title: "Decoration",
    subtitle: "Design Your Dream",
    desc: "Transforming venues into magical wonderlands. From intimate floral setups to grand mandap decorations — we bring your vision to life.",
    price: "Starting from ₹10,000",
    tag: "Trending",
    tagColor: "bg-pink-500",
    highlights: ["Floral Design", "Mandap Setup", "LED Lighting", "Theme Decor"],
    rating: 4.9,
    reviews: 312,
    img: "https://images.unsplash.com/photo-1464366400600-7168b8af9bc3?w=800",
    styles: [
      { id: 1, name: "Royal Marigold", desc: "Traditional Tamil marigold theme", price: 25000, img: "https://images.unsplash.com/photo-1464366400600-7168b8af9bc3?w=600", specs: [{ label: "Flowers Used", value: "Fresh Marigold + Roses" }, { label: "Mandap", value: "Traditional Setup" }, { label: "Stage Decor", value: "Full Backdrop" }, { label: "Table Settings", value: "10 Tables" }, { label: "Entrance Decor", value: "Flower Arch Included" }, { label: "Setup Time", value: "1 Day Before" }] },
      { id: 2, name: "Floral Fantasy", desc: "All-fresh flowers luxury setup", price: 40000, img: "https://images.unsplash.com/photo-1519225421980-715cb0215aed?w=600", specs: [{ label: "Flowers Used", value: "Imported + Local Fresh" }, { label: "Mandap", value: "Premium Floral Canopy" }, { label: "Stage Decor", value: "360° Floral Backdrop" }, { label: "Table Settings", value: "20 Tables" }, { label: "Centerpieces", value: "Custom Floral" }, { label: "Setup Time", value: "2 Days Before" }] },
      { id: 3, name: "White & Gold", desc: "Elegant modern white theme", price: 35000, img: "https://images.unsplash.com/photo-1511795409834-ef04bbd61622?w=600", specs: [{ label: "Color Theme", value: "White + Gold" }, { label: "Flowers", value: "White Roses + Lilies" }, { label: "Mandap", value: "Gold Frame Setup" }, { label: "Draping", value: "White Fabric Draping" }, { label: "LED Lights", value: "Warm Gold Lights" }, { label: "Table Settings", value: "15 Tables" }] },
      { id: 4, name: "LED Wonderland", desc: "Full LED light decoration", price: 30000, img: "https://images.unsplash.com/photo-1530103862676-de8c9debad1d?w=600", specs: [{ label: "LED Coverage", value: "Full Venue" }, { label: "LED Types", value: "Fairy + Strip + Spotlights" }, { label: "Color Options", value: "Custom RGB" }, { label: "Stage Lighting", value: "Moving Heads" }, { label: "Flowers", value: "Minimal Accent" }, { label: "Power Setup", value: "Included" }] },
      { id: 5, name: "Bohemian Garden", desc: "Outdoor garden boho style", price: 28000, img: "https://images.unsplash.com/photo-1478146059778-26028b07395a?w=600", specs: [{ label: "Style", value: "Outdoor Boho" }, { label: "Materials", value: "Macrame + Pampas Grass" }, { label: "Flowers", value: "Wildflowers + Greenery" }, { label: "Seating", value: "Rustic Setup" }, { label: "Fairy Lights", value: "String Lights Included" }, { label: "Suitable For", value: "Garden / Terrace Venue" }] },
      { id: 6, name: "Pink & Roses", desc: "Romantic rose-themed setup", price: 32000, img: "https://images.unsplash.com/photo-1465495976277-4387d4b0b4c6?w=600", specs: [{ label: "Color Theme", value: "Blush Pink + White" }, { label: "Flowers", value: "Fresh Roses (2000+)" }, { label: "Mandap", value: "Rose Canopy" }, { label: "Photo Booth", value: "Rose Wall Included" }, { label: "Table Settings", value: "15 Tables" }, { label: "Petals", value: "Aisle Petal Setup" }] },
    ],
  },
  {
    id: 4,
    icon: "🍽️",
    title: "Catering",
    subtitle: "Flavours That Wow",
    desc: "Multi-cuisine catering with experienced chefs. From traditional Tamil Sadhya to continental buffets — crafted to delight every palate.",
    price: "Starting from ₹300/plate",
    tag: "Best Value",
    tagColor: "bg-amber-500",
    highlights: ["Multi-Cuisine", "Live Counters", "Hygienic Kitchen", "Custom Menu"],
    rating: 4.7,
    reviews: 421,
    img: "https://images.unsplash.com/photo-1555244162-803834f70033?w=800",
    styles: [
      { id: 1, name: "Tamil Sadhya", desc: "Traditional banana leaf feast", price: 350, img: "https://images.unsplash.com/photo-1555244162-803834f70033?w=600", specs: [{ label: "Price", value: "₹350 per plate" }, { label: "Min Order", value: "50 Plates" }, { label: "Items", value: "15+ Traditional Items" }, { label: "Served On", value: "Banana Leaf" }, { label: "Includes", value: "Rice, Curries, Payasam" }, { label: "Service Staff", value: "1 per 25 guests" }] },
      { id: 2, name: "North Indian Buffet", desc: "Paneer, biryani, naan & more", price: 450, img: "https://images.unsplash.com/photo-1567620905732-2d1ec7ab7445?w=600", specs: [{ label: "Price", value: "₹450 per plate" }, { label: "Min Order", value: "100 Plates" }, { label: "Items", value: "20+ Items" }, { label: "Includes", value: "Biryani, Paneer, Naan, Dal" }, { label: "Desserts", value: "Gulab Jamun + Ice Cream" }, { label: "Service Style", value: "Buffet Counter" }] },
      { id: 3, name: "Continental", desc: "International cuisine buffet", price: 700, img: "https://images.unsplash.com/photo-1565299624946-b28f40a0ae38?w=600", specs: [{ label: "Price", value: "₹700 per plate" }, { label: "Min Order", value: "50 Plates" }, { label: "Items", value: "25+ Items" }, { label: "Includes", value: "Pasta, Pizza, Grills, Salads" }, { label: "Desserts", value: "Pastries + Mousse" }, { label: "Welcome Drink", value: "Mocktails Included" }] },
      { id: 4, name: "Live Counter", desc: "Dosa, chaat, pasta live stations", price: 600, img: "https://images.unsplash.com/photo-1540189549336-e6e99c3679fe?w=600", specs: [{ label: "Price", value: "₹600 per plate" }, { label: "Min Order", value: "75 Plates" }, { label: "Live Stations", value: "3 Stations" }, { label: "Station Options", value: "Dosa, Chaat, Pasta" }, { label: "Chef Per Station", value: "1 Dedicated Chef" }, { label: "Customizable", value: "Yes" }] },
      { id: 5, name: "Veg Premium", desc: "Premium veg multi-cuisine", price: 500, img: "https://images.unsplash.com/photo-1504674900247-0877df9cc836?w=600", specs: [{ label: "Price", value: "₹500 per plate" }, { label: "Min Order", value: "50 Plates" }, { label: "Items", value: "18+ Veg Items" }, { label: "Jain Option", value: "Available" }, { label: "Desserts", value: "3 Varieties" }, { label: "Welcome Drink", value: "Included" }] },
      { id: 6, name: "Non-Veg Special", desc: "Full non-veg with seafood", price: 650, img: "https://images.unsplash.com/photo-1547592180-85f173990554?w=600", specs: [{ label: "Price", value: "₹650 per plate" }, { label: "Min Order", value: "75 Plates" }, { label: "Items", value: "20+ Items" }, { label: "Includes", value: "Chicken, Mutton, Seafood" }, { label: "Biryani", value: "Dum Biryani Included" }, { label: "Desserts", value: "2 Varieties" }] },
    ],
  },
  {
    id: 5,
    icon: "🏨",
    title: "Venue Booking",
    subtitle: "Find Your Perfect Space",
    desc: "Curated venues across Coimbatore — from intimate garden settings to grand banquet halls. Best price guaranteed, zero hassle.",
    price: "Starting from ₹20,000",
    tag: "Premium",
    tagColor: "bg-blue-500",
    highlights: ["100+ Venues", "Price Match", "Site Visit", "AC Halls"],
    rating: 4.8,
    reviews: 156,
    img: "https://images.unsplash.com/photo-1530103862676-de8c9debad1d?w=800",
    styles: [
      { id: 1, name: "Grand Banquet Hall", desc: "AC hall for 300–500 guests", price: 60000, img: "https://images.unsplash.com/photo-1530103862676-de8c9debad1d?w=600", specs: [{ label: "Capacity", value: "300–500 Guests" }, { label: "AC", value: "Full AC Hall" }, { label: "Parking", value: "200+ Vehicles" }, { label: "Booking Days", value: "2 Days Included" }, { label: "Catering", value: "Outside Allowed" }, { label: "Green Room", value: "2 Rooms" }] },
      { id: 2, name: "Garden Venue", desc: "Open-air garden setting", price: 35000, img: "https://images.unsplash.com/photo-1464366400600-7168b8af9bc3?w=600", specs: [{ label: "Capacity", value: "150–250 Guests" }, { label: "Type", value: "Open Air Garden" }, { label: "Parking", value: "100+ Vehicles" }, { label: "Booking Days", value: "1 Day" }, { label: "Catering", value: "Outside Allowed" }, { label: "Power Backup", value: "Generator Included" }] },
      { id: 3, name: "Beach / Resort", desc: "Scenic resort venue", price: 80000, img: "https://images.unsplash.com/photo-1519225421980-715cb0215aed?w=600", specs: [{ label: "Capacity", value: "100–300 Guests" }, { label: "Location", value: "Resort / Beach Side" }, { label: "Accommodation", value: "Rooms Available" }, { label: "Booking Days", value: "2 Days" }, { label: "Catering", value: "In-house Preferred" }, { label: "Swimming Pool", value: "Access Included" }] },
      { id: 4, name: "Heritage / Palace", desc: "Royal heritage property", price: 100000, img: "https://images.unsplash.com/photo-1511795409834-ef04bbd61622?w=600", specs: [{ label: "Capacity", value: "200–400 Guests" }, { label: "Type", value: "Heritage Building" }, { label: "Rooms", value: "10+ Rooms" }, { label: "Booking Days", value: "3 Days" }, { label: "Exclusivity", value: "Full Property" }, { label: "Decor Permission", value: "Full Permission" }] },
      { id: 5, name: "Rooftop Venue", desc: "Terrace with city view", price: 45000, img: "https://images.unsplash.com/photo-1519741497674-611481863552?w=600", specs: [{ label: "Capacity", value: "100–200 Guests" }, { label: "Type", value: "Open Rooftop" }, { label: "View", value: "City Skyline" }, { label: "Booking Days", value: "1 Day" }, { label: "Weather Backup", value: "Tent Available" }, { label: "Catering", value: "Outside Allowed" }] },
      { id: 6, name: "Temple / Traditional", desc: "Traditional marriage hall", price: 25000, img: "https://images.unsplash.com/photo-1465495976277-4387d4b0b4c6?w=600", specs: [{ label: "Capacity", value: "100–300 Guests" }, { label: "Type", value: "Marriage Hall" }, { label: "AC", value: "Available" }, { label: "Muhurtham Support", value: "Yes" }, { label: "Booking Days", value: "1 Day" }, { label: "Catering Kitchen", value: "In-house Available" }] },
    ],
  },
  {
    id: 6,
    icon: "💄",
    title: "Makeup Artist",
    subtitle: "Look Absolutely Stunning",
    desc: "Celebrity makeup artists specializing in bridal looks. Airbrush, HD, traditional — we make you look stunning from the first ritual to the last dance.",
    price: "Starting from ₹3,000",
    tag: "New",
    tagColor: "bg-emerald-500",
    highlights: ["Bridal Specialist", "Airbrush Makeup", "HD Finish", "Trial Session"],
    rating: 4.9,
    reviews: 98,
    img: "https://images.unsplash.com/photo-1522337360788-8b13dee7a37e?w=800",
    styles: [
      { id: 1, name: "Traditional Bridal", desc: "Classic Tamil bridal look", price: 10000, img: "https://images.unsplash.com/photo-1522337360788-8b13dee7a37e?w=600", specs: [{ label: "Makeup Type", value: "Traditional Tamil" }, { label: "Products", value: "MAC + Kryolan" }, { label: "Hair Styling", value: "Included" }, { label: "Saree Draping", value: "Included" }, { label: "Trial Session", value: "1 Session" }, { label: "Home Visit", value: "Available" }] },
      { id: 2, name: "HD Bridal", desc: "Flawless HD camera-ready look", price: 15000, img: "https://images.unsplash.com/photo-1487412947147-5cebf100ffc2?w=600", specs: [{ label: "Makeup Type", value: "HD Professional" }, { label: "Products", value: "Charlotte Tilbury + MAC" }, { label: "Hair Styling", value: "Full Bridal Style" }, { label: "Saree Draping", value: "Included" }, { label: "Trial Session", value: "1 Session" }, { label: "Touch-up Kit", value: "Provided" }] },
      { id: 3, name: "Airbrush Bridal", desc: "Celebrity-grade airbrush finish", price: 25000, img: "https://images.unsplash.com/photo-1570172619644-dfd03ed5d881?w=600", specs: [{ label: "Makeup Type", value: "Airbrush Professional" }, { label: "Products", value: "Temptu + Charlotte Tilbury" }, { label: "Hair Styling", value: "Celebrity Styling" }, { label: "Saree Draping", value: "Included" }, { label: "Trial Sessions", value: "2 Sessions" }, { label: "All-Day Touch-up", value: "Artist Stays" }] },
      { id: 4, name: "Dewy & Natural", desc: "Fresh glowing natural look", price: 8000, img: "https://images.unsplash.com/photo-1516975080664-ed2fc6a32937?w=600", specs: [{ label: "Makeup Type", value: "Natural / Dewy" }, { label: "Products", value: "Premium Organic" }, { label: "Hair Styling", value: "Included" }, { label: "Finish", value: "Glowing Skin" }, { label: "Duration", value: "2 hrs" }, { label: "Home Visit", value: "Available" }] },
      { id: 5, name: "Smokey Glam", desc: "Bold dramatic evening look", price: 7000, img: "https://images.unsplash.com/photo-1594744803329-e58b31de8bf5?w=600", specs: [{ label: "Makeup Type", value: "Smokey / Glam" }, { label: "Products", value: "MAC + NYX" }, { label: "Hair Styling", value: "Included" }, { label: "Eyelashes", value: "Premium Lashes" }, { label: "Duration", value: "1.5 hrs" }, { label: "Suitable For", value: "Reception / Party" }] },
      { id: 6, name: "Saree + Full Glam", desc: "Makeup + saree draping combo", price: 12000, img: "https://images.unsplash.com/photo-1583241800698-e8ab01830a22?w=600", specs: [{ label: "Includes", value: "Makeup + Saree Draping" }, { label: "Makeup Type", value: "Full Glam Bridal" }, { label: "Saree Styles", value: "Tamilian / Nivi / Gujarati" }, { label: "Hair Styling", value: "Included" }, { label: "Duration", value: "3 hrs" }, { label: "Home Visit", value: "Included" }] },
    ],
  },
  {
    id: 7,
    icon: "🌿",
    title: "Mehendi Artist",
    subtitle: "Art On Your Hands",
    desc: "Experienced mehendi artists creating intricate bridal designs. Arabic, Rajasthani, Indo-Arabic styles — beautiful art for your special day.",
    price: "Starting from ₹2,000",
    tag: "Trending",
    tagColor: "bg-green-600",
    highlights: ["Organic Paste", "Deep Dark Color", "Home Visit", "Arabic Style"],
    rating: 4.8,
    reviews: 143,
    img: "https://plus.unsplash.com/premium_photo-1682092018999-2c8fcfe944f3?w=1000",
    styles: [
      { id: 1, name: "Arabic Style", desc: "Bold floral Arabic patterns", price: 3000, img: "https://plus.unsplash.com/premium_photo-1682092018999-2c8fcfe944f3?w=1000", specs: [{ label: "Coverage", value: "Both Hands" }, { label: "Style", value: "Arabic Floral" }, { label: "Paste Type", value: "100% Organic" }, { label: "Color", value: "Dark Brown-Black" }, { label: "Dry Time", value: "30 Minutes" }, { label: "Home Visit", value: "Included" }] },
      { id: 2, name: "Rajasthani Bridal", desc: "Dense full-hand Rajasthani", price: 5000, img: "https://plus.unsplash.com/premium_photo-1661896237419-6e232b54eefc?w=800", specs: [{ label: "Coverage", value: "Hands + Feet" }, { label: "Style", value: "Dense Rajasthani" }, { label: "Paste Type", value: "Organic + Fragrant" }, { label: "Duration", value: "3–4 hrs" }, { label: "Artists", value: "2 Artists" }, { label: "Home Visit", value: "Included" }] },
      { id: 3, name: "Indo-Arabic Fusion", desc: "Mix of both styles", price: 4000, img: "https://images.unsplash.com/photo-1505932794465-147d1f1b2c97?w=800", specs: [{ label: "Coverage", value: "Both Hands + Wrist" }, { label: "Style", value: "Indo-Arabic Fusion" }, { label: "Duration", value: "2–3 hrs" }, { label: "Paste Type", value: "Organic" }, { label: "Color", value: "Deep Dark" }, { label: "Home Visit", value: "Included" }] },
      { id: 4, name: "Portrait Mehendi", desc: "Bride & groom portrait design", price: 7000, img: "https://images.unsplash.com/photo-1525135850648-b42365991054?w=800", specs: [{ label: "Coverage", value: "Full Hands + Arms" }, { label: "Special Feature", value: "Couple Portrait" }, { label: "Duration", value: "5–6 hrs" }, { label: "Artists", value: "Senior Artist" }, { label: "Paste Type", value: "Premium Organic" }, { label: "Home Visit", value: "Included" }] },
      { id: 5, name: "Minimalist Modern", desc: "Simple elegant patterns", price: 2000, img: "https://plus.unsplash.com/premium_photo-1670745084868-7b4f727cc934?w=800", specs: [{ label: "Coverage", value: "One Hand or Both" }, { label: "Style", value: "Minimalist Lines" }, { label: "Duration", value: "45 min – 1 hr" }, { label: "Paste Type", value: "Organic" }, { label: "Suitable For", value: "Bridesmaids / Party" }, { label: "Home Visit", value: "Available" }] },
      { id: 6, name: "Full Arm Bridal", desc: "Hands + arms full coverage", price: 8000, img: "https://images.unsplash.com/photo-1624504761718-be4d634f4624?w=800", specs: [{ label: "Coverage", value: "Hands + Full Arms + Feet" }, { label: "Duration", value: "6–7 hrs" }, { label: "Artists", value: "2 Senior Artists" }, { label: "Paste Type", value: "Premium Organic" }, { label: "Touch-up", value: "Next Day Included" }, { label: "Home Visit", value: "Included" }] },
    ],
  },
  {
    id: 8,
    icon: "👑",
    title: "Wedding Planner",
    subtitle: "Your Personal Coordinator",
    desc: "End-to-end wedding planning by expert coordinators. From vendor management to day-of coordination — we handle everything so you enjoy every moment.",
    price: "Starting from ₹25,000",
    tag: "Premium",
    tagColor: "bg-yellow-600",
    highlights: ["Dedicated Planner", "Budget Tracker", "Vendor Network", "24/7 Support"],
    rating: 4.9,
    reviews: 87,
    img: "https://images.unsplash.com/photo-1511795409834-ef04bbd61622?w=800",
    styles: [
      { id: 1, name: "Full Wedding Planning", desc: "Complete A–Z planning", price: 75000, img: "https://images.unsplash.com/photo-1511795409834-ef04bbd61622?w=600", specs: [{ label: "Planning Duration", value: "3–12 Months" }, { label: "Dedicated Planner", value: "1 Senior Planner" }, { label: "Vendors Managed", value: "All Vendors" }, { label: "Meetings", value: "Unlimited" }, { label: "Day Coordination", value: "Full Team" }, { label: "Wedding Portal", value: "Included" }] },
      { id: 2, name: "Day Coordination Only", desc: "Only wedding day management", price: 15000, img: "https://images.unsplash.com/photo-1519741497674-611481863552?w=600", specs: [{ label: "Service", value: "Wedding Day Only" }, { label: "Coordinators", value: "2 on Site" }, { label: "Timeline", value: "Custom Schedule" }, { label: "Vendor Liaison", value: "Included" }, { label: "Pre-Meeting", value: "2 Planning Calls" }, { label: "Emergency Support", value: "24/7" }] },
      { id: 3, name: "Vendor Management", desc: "Find & manage all vendors", price: 25000, img: "https://images.unsplash.com/photo-1464366400600-7168b8af9bc3?w=600", specs: [{ label: "Vendors", value: "All Categories" }, { label: "Negotiation", value: "Included" }, { label: "Contracts", value: "Reviewed" }, { label: "Meetings", value: "10 Included" }, { label: "Savings", value: "Avg 15–20%" }, { label: "Support", value: "WhatsApp 24/7" }] },
      { id: 4, name: "Budget Planning", desc: "Optimize your wedding budget", price: 10000, img: "https://images.unsplash.com/photo-1519225421980-715cb0215aed?w=600", specs: [{ label: "Budget Analysis", value: "Detailed Report" }, { label: "Category Breakdown", value: "All Sections" }, { label: "Savings Tips", value: "Personalized" }, { label: "Sessions", value: "3 Planning Sessions" }, { label: "Vendor Discounts", value: "Network Access" }, { label: "Tracker", value: "Excel + Portal" }] },
      { id: 5, name: "Destination Wedding", desc: "Outstation wedding planning", price: 100000, img: "https://images.unsplash.com/photo-1530103862676-de8c9debad1d?w=600", specs: [{ label: "Locations", value: "Pan India" }, { label: "Team", value: "2 Planners" }, { label: "Guest Management", value: "Travel + Stay" }, { label: "Local Vendors", value: "Managed" }, { label: "Duration", value: "3-Day Events" }, { label: "Logistics", value: "Full Support" }] },
      { id: 6, name: "Honeymoon Planning", desc: "Post-wedding travel package", price: 20000, img: "https://images.unsplash.com/photo-1465495976277-4387d4b0b4c6?w=600", specs: [{ label: "Destinations", value: "Domestic + International" }, { label: "Duration", value: "5–14 Days" }, { label: "Includes", value: "Hotel + Flight" }, { label: "Activities", value: "Curated Experiences" }, { label: "Budget Options", value: "All Ranges" }, { label: "Support", value: "24/7 Travel Helpline" }] },
    ],
  },
  {
    id: 9,
    icon: "💌",
    title: "Invitation Cards",
    subtitle: "First Impressions Matter",
    desc: "Stunning physical & digital wedding invitations. Traditional Tamil designs, modern minimalist styles, and animated e-invites that wow your guests.",
    price: "Starting from ₹1,500",
    tag: "New",
    tagColor: "bg-fuchsia-500",
    highlights: ["Custom Design", "Tamil & English", "WhatsApp E-Invites", "Fast Delivery"],
    rating: 4.7,
    reviews: 201,
    img: "https://images.unsplash.com/photo-1607344645866-009c320b63e0?w=800",
    styles: [
      { id: 1, name: "Royal Gold", desc: "Gold-embossed luxury card", price: 8000, img: "https://images.unsplash.com/photo-1607344645866-009c320b63e0?w=600", specs: [{ label: "Quantity", value: "100 Cards" }, { label: "Size", value: "A5 (14.8 × 21 cm)" }, { label: "Paper", value: "300 GSM Matt" }, { label: "Finish", value: "Gold Foil Embossing" }, { label: "Language", value: "Tamil + English" }, { label: "Delivery", value: "5 Days" }] },
      { id: 2, name: "Traditional Tamil", desc: "Kolam & temple motif design", price: 5000, img: "https://images.unsplash.com/photo-1513519245088-0e12902e5a38?w=600", specs: [{ label: "Quantity", value: "100 Cards" }, { label: "Size", value: "A5 (14.8 × 21 cm)" }, { label: "Paper", value: "250 GSM Glossy" }, { label: "Design", value: "Kolam + Temple Motif" }, { label: "Language", value: "Tamil + English" }, { label: "Delivery", value: "4 Days" }] },
      { id: 3, name: "Minimalist Modern", desc: "Clean elegant typography", price: 4000, img: "https://images.unsplash.com/photo-1578269174936-2709b6aeb913?w=600", specs: [{ label: "Quantity", value: "100 Cards" }, { label: "Size", value: "DL (10 × 21 cm)" }, { label: "Paper", value: "300 GSM Matte White" }, { label: "Design", value: "Clean Typography" }, { label: "Language", value: "English" }, { label: "Delivery", value: "3 Days" }] },
      { id: 4, name: "Floral Pastel", desc: "Soft floral watercolor design", price: 5500, img: "https://images.unsplash.com/photo-1500462918059-b1a0cb512f1d?w=600", specs: [{ label: "Quantity", value: "100 Cards" }, { label: "Size", value: "A5 (14.8 × 21 cm)" }, { label: "Paper", value: "280 GSM Soft Touch" }, { label: "Design", value: "Watercolor Florals" }, { label: "Language", value: "Tamil + English" }, { label: "Delivery", value: "4 Days" }] },
      { id: 5, name: "Animated E-Invite", desc: "WhatsApp animated digital card", price: 2000, img: "https://images.unsplash.com/photo-1470229722913-7c0e2dbbafd3?w=600", specs: [{ label: "Format", value: "MP4 Video / GIF" }, { label: "Duration", value: "15–30 seconds" }, { label: "Resolution", value: "1080p HD" }, { label: "Music", value: "Background Music" }, { label: "Sharing", value: "WhatsApp Ready" }, { label: "Delivery", value: "2 Days" }] },
      { id: 6, name: "Royal Velvet Box", desc: "Premium box card with inserts", price: 15000, img: "https://images.unsplash.com/photo-1519741497674-611481863552?w=600", specs: [{ label: "Quantity", value: "50 Box Sets" }, { label: "Includes", value: "Box + Card + Inserts" }, { label: "Material", value: "Velvet Box" }, { label: "Extras", value: "Dry Fruits / Sweets Insert" }, { label: "Personalization", value: "Full Custom" }, { label: "Delivery", value: "7 Days" }] },
    ],
  },
  {
    id: 10,
    icon: "🐴",
    title: "Baraat Decoration",
    subtitle: "Grand Entry Awaits",
    desc: "Make a royal entry! Decorated horses, vintage cars, and flower-decorated vehicles for the most unforgettable baraat procession.",
    price: "Starting from ₹8,000",
    tag: "Unique",
    tagColor: "bg-orange-500",
    highlights: ["Decorated Horse", "Vintage Cars", "Band Party", "Dhol Players"],
    rating: 4.6,
    reviews: 62,
    img: "https://images.unsplash.com/photo-1744891470493-44321ef136a2?w=800",
    styles: [
      { id: 1, name: "White Horse Entry", desc: "Decorated white horse procession", price: 15000, img: "https://images.unsplash.com/photo-1744891470493-44321ef136a2?w=800", specs: [{ label: "Horse", value: "1 White Horse" }, { label: "Decoration", value: "Full Flower Decor" }, { label: "Mahout", value: "Experienced Handler" }, { label: "Band Party", value: "10 Members" }, { label: "Duration", value: "1.5 hrs" }, { label: "Area", value: "Coimbatore + 50km" }] },
      { id: 2, name: "Vintage Car Entry", desc: "Classic decorated vintage car", price: 12000, img: "https://images.unsplash.com/photo-1511795409834-ef04bbd61622?w=600", specs: [{ label: "Car", value: "1 Vintage Car" }, { label: "Decoration", value: "Full Flower Decor" }, { label: "Driver", value: "Professional" }, { label: "Ribbon", value: "Just Married Setup" }, { label: "Duration", value: "3 hrs" }, { label: "Distance", value: "Up to 100km" }] },
      { id: 3, name: "Flower Chariot", desc: "Floral chariot grand entry", price: 20000, img: "https://images.unsplash.com/photo-1519225421980-715cb0215aed?w=600", specs: [{ label: "Chariot", value: "Fully Decorated" }, { label: "Flowers", value: "2000+ Fresh Flowers" }, { label: "Theme", value: "Royal / Temple" }, { label: "Band Party", value: "15 Members" }, { label: "Duration", value: "2 hrs" }, { label: "LED Lights", value: "Night Lighting" }] },
      { id: 4, name: "DJ Truck Baraat", desc: "DJ on wheels with lights", price: 18000, img: "https://images.unsplash.com/photo-1478146059778-26028b07395a?w=600", specs: [{ label: "DJ Truck", value: "Full Setup Truck" }, { label: "Sound", value: "2000W System" }, { label: "LED Lights", value: "Full Rig" }, { label: "DJ", value: "Professional DJ" }, { label: "Duration", value: "2 hrs Procession" }, { label: "Dhol", value: "2 Players" }] },
      { id: 5, name: "Elephant Entry", desc: "Royal elephant procession", price: 35000, img: "https://images.unsplash.com/photo-1530103862676-de8c9debad1d?w=600", specs: [{ label: "Elephant", value: "1 Decorated Elephant" }, { label: "Mahout", value: "Certified Handler" }, { label: "Decoration", value: "Traditional Ornaments" }, { label: "Band Party", value: "20 Members" }, { label: "Permits", value: "Arranged" }, { label: "Duration", value: "1 hr" }] },
      { id: 6, name: "Full Grand Baraat", desc: "Horse + car + band + DJ combo", price: 45000, img: "https://images.unsplash.com/photo-1464366400600-7168b8af9bc3?w=600", specs: [{ label: "Includes", value: "Horse + Vintage Car" }, { label: "Band Party", value: "20 Members" }, { label: "DJ Truck", value: "Included" }, { label: "Dhol Players", value: "4 Players" }, { label: "Flower Shower", value: "Drone Petal Drop" }, { label: "Duration", value: "3 hrs Full Procession" }] },
    ],
  },
  {
    id: 11,
    icon: "🎬",
    title: "Videography",
    subtitle: "Relive Every Moment",
    desc: "Cinematic wedding films that capture the emotion, drama, and beauty of your day. 4K drone footage, highlight reels & full ceremony recordings.",
    price: "Starting from ₹10,000",
    tag: "Most Popular",
    tagColor: "bg-red-500",
    highlights: ["4K Cinematic", "Drone Footage", "Highlight Reel", "Color Grading"],
    rating: 4.8,
    reviews: 176,
    img: "https://images.unsplash.com/photo-1574717024653-61fd2cf4d44d?w=800",
    styles: [
      { id: 1, name: "Cinematic Film", desc: "Bollywood-style cinematic edit", price: 20000, img: "https://images.unsplash.com/photo-1574717024653-61fd2cf4d44d?w=600", specs: [{ label: "Coverage", value: "Full Day (8 hrs)" }, { label: "Camera", value: "Sony FX3 4K" }, { label: "Videographers", value: "2" }, { label: "Highlight Reel", value: "5 Minutes" }, { label: "Full Film", value: "30–45 Minutes" }, { label: "Delivery", value: "14 Days" }] },
      { id: 2, name: "Documentary Style", desc: "Real, unscripted storytelling", price: 15000, img: "https://images.unsplash.com/photo-1489599849927-2ee91cede3ba?w=600", specs: [{ label: "Coverage", value: "Full Day" }, { label: "Style", value: "Raw Documentary" }, { label: "Videographers", value: "1" }, { label: "Highlight Reel", value: "3 Minutes" }, { label: "Full Film", value: "60+ Minutes" }, { label: "Delivery", value: "10 Days" }] },
      { id: 3, name: "Drone Aerial Film", desc: "Stunning aerial wedding film", price: 25000, img: "https://images.unsplash.com/photo-1536240478700-b869ad10e128?w=600", specs: [{ label: "Drone", value: "DJI Mavic 3 Pro" }, { label: "Drone Pilot", value: "Licensed" }, { label: "Resolution", value: "4K / 5.1K" }, { label: "Aerial Clips", value: "20+" }, { label: "Combined Film", value: "Ground + Aerial" }, { label: "Delivery", value: "14 Days" }] },
      { id: 4, name: "Instagram Reels", desc: "Short reels for social media", price: 8000, img: "https://images.unsplash.com/photo-1560169897-fc0cdbdfa4d5?w=600", specs: [{ label: "Reels Delivered", value: "5 Reels" }, { label: "Duration Each", value: "30–60 seconds" }, { label: "Format", value: "9:16 Vertical" }, { label: "Music", value: "Trending Tracks" }, { label: "Captions", value: "Included" }, { label: "Delivery", value: "5 Days" }] },
      { id: 5, name: "Full Coverage", desc: "Complete ceremony recording", price: 18000, img: "https://images.unsplash.com/photo-1519741497674-611481863552?w=600", specs: [{ label: "Coverage", value: "Full Day (10 hrs)" }, { label: "Cameras", value: "3 Angles" }, { label: "Muhurtham", value: "Dedicated Close-up" }, { label: "Full Film", value: "2+ Hours" }, { label: "Highlight", value: "5 Min Reel" }, { label: "Delivery", value: "14 Days" }] },
      { id: 6, name: "Premium Package", desc: "Film + reels + drone combo", price: 35000, img: "https://images.unsplash.com/photo-1511795409834-ef04bbd61622?w=600", specs: [{ label: "Includes", value: "Film + Reels + Drone" }, { label: "Videographers", value: "3 Team" }, { label: "Highlight Reel", value: "8 Minutes" }, { label: "Instagram Reels", value: "5 Included" }, { label: "Drone Coverage", value: "Full Day" }, { label: "Delivery", value: "14 Days" }] },
    ],
  },
  {
    id: 12,
    icon: "🎂",
    title: "Wedding Cake",
    subtitle: "Sweet Celebrations",
    desc: "Custom designed wedding cakes by master bakers. Multi-tier designs, floral fondant, themed cakes — every slice is a work of art.",
    price: "Starting from ₹3,500",
    tag: "New",
    tagColor: "bg-pink-400",
    highlights: ["Belgian Chocolate", "Eggless Available", "Custom Design", "Free Delivery"],
    rating: 4.8,
    reviews: 119,
    img: "https://images.unsplash.com/photo-1535254973040-607b474cb50d?w=800",
    styles: [
      { id: 1, name: "Floral White Cake", desc: "Elegant white fondant floral", price: 6000, img: "https://images.unsplash.com/photo-1535254973040-607b474cb50d?w=600", specs: [{ label: "Tiers", value: "3 Tier" }, { label: "Weight", value: "3 kg" }, { label: "Serves", value: "30–40 People" }, { label: "Flavour", value: "Vanilla / Strawberry" }, { label: "Eggless", value: "Available" }, { label: "Delivery", value: "Free in Coimbatore" }] },
      { id: 2, name: "Rustic Naked Cake", desc: "Natural rustic buttercream", price: 4500, img: "https://images.unsplash.com/photo-1578985545062-69928b1d9587?w=600", specs: [{ label: "Tiers", value: "2 Tier" }, { label: "Weight", value: "2 kg" }, { label: "Serves", value: "20–25 People" }, { label: "Flavour", value: "Chocolate / Vanilla" }, { label: "Topping", value: "Fresh Fruits" }, { label: "Eggless", value: "Available" }] },
      { id: 3, name: "Gold Drip Cake", desc: "Luxury gold drip design", price: 8000, img: "https://images.unsplash.com/photo-1464349153735-7db50ed83c84?w=600", specs: [{ label: "Tiers", value: "3 Tier" }, { label: "Weight", value: "4 kg" }, { label: "Serves", value: "40–50 People" }, { label: "Flavour", value: "Dark Chocolate" }, { label: "Finish", value: "Edible Gold Drip" }, { label: "Eggless", value: "Available" }] },
      { id: 4, name: "Floral 3-Tier", desc: "3-tier fresh flower cake", price: 10000, img: "https://images.unsplash.com/photo-1519869325930-281384150729?w=600", specs: [{ label: "Tiers", value: "3 Tier" }, { label: "Weight", value: "5 kg" }, { label: "Serves", value: "50–60 People" }, { label: "Topping", value: "Fresh Edible Flowers" }, { label: "Flavour", value: "Red Velvet / Vanilla" }, { label: "Tasting Session", value: "Included" }] },
      { id: 5, name: "Traditional Sweet", desc: "Traditional Indian sweet cake", price: 3500, img: "https://images.unsplash.com/photo-1562777717-dc6984f65a63?w=600", specs: [{ label: "Tiers", value: "1 Tier" }, { label: "Weight", value: "2 kg" }, { label: "Serves", value: "20 People" }, { label: "Flavour", value: "Kesar / Badam" }, { label: "Eggless", value: "Always" }, { label: "Delivery", value: "Free" }] },
      { id: 6, name: "Royal 5-Tier", desc: "Grand 5-tier luxury cake", price: 18000, img: "https://images.unsplash.com/photo-1621303837174-89787a7d4729?w=600", specs: [{ label: "Tiers", value: "5 Tier" }, { label: "Weight", value: "10 kg" }, { label: "Serves", value: "100–120 People" }, { label: "Flavours", value: "4 Different Flavours" }, { label: "Design", value: "Custom Theme" }, { label: "Setup", value: "Baker Comes & Sets Up" }] },
    ],
  },
];

async function seed() {
  try {
    await mongoose.connect(process.env.MONGO_URI);
    console.log("MongoDB Connected ✅");

    await Service.deleteMany({});
    console.log("Old services cleared 🗑️");

    await Service.insertMany(services);
    console.log(`✅ Seeded ${services.length} services successfully!`);

    mongoose.disconnect();
  } catch (err) {
    console.error("Seed failed:", err);
    mongoose.disconnect();
    process.exit(1);
  }
}

seed();